### ISSUE TITLE
Panic while joining a network: validator does not exist

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#1524]
The following panic occurred while joining the omega testnet (this is sporadic and doesn't always occur).

```
halo      | 24-07-18 05:24:43.469 ERRO Finalize req failed [BUG]                height=434001 err="validator does not exist"
halo      | 24-07-18 05:24:43.470 ERRO error in proxyAppConn.FinalizeBlock      module=consensus err="validator does not exist"
halo      | 24-07-18 05:24:43.470 ERRO !! Fatal error occurred, app died️ unexpectedly !! err="create comet node: create node: error during handshake: error on replay: validator does not exist" stacktrace="[errors.go:39 start.go:250 start.go:145 start.go:61 cmd.go:50 command.go:985 command.go:1117 command.go:1041 command.go:1034 cmd.go:34 main.go:10 proc.go:271 asm_arm64.s:1222]"

halo      | panic: Failed to process committed block (434001:D5033D3BC85314420BB183B7BDA183332470FA9C54025793B25CBB302B59F706): validator does not exist
halo      |
halo      | goroutine 312 [running]:
halo      | github.com/cometbft/cometbft/blocksync.(*Reactor).poolRoutine(0xc002063400, 0x1)
halo      | 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.10/blocksync/reactor.go:552 +0x1946
halo      | github.com/cometbft/cometbft/blocksync.(*Reactor).SwitchToBlockSync.func1()
halo      | 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.10/blocksync/reactor.go:161 +0x57
halo      | created by github.com/cometbft/cometbft/blocksync.(*Reactor).SwitchToBlockSync in goroutine 191
halo      | 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.10/blocksync/reactor.go:159 +0xfb

halo exited with code 1
```
When restarting the node, it occurred again. 
```
halo      | 24-07-18 05:26:32.657 ERRO Finalize req failed [BUG]                height=434001 err="validator does not exist"
halo      | 24-07-18 05:26:32.657 ERRO error in proxyAppConn.FinalizeBlock      module=consensus err="validator does not exist"
halo      | 24-07-18 05:26:32.657 ERRO !! Fatal error occurred, app died️ unexpectedly !! err="create comet node: create node: error during handshake: error on replay: validator does not exist" stacktrace="[errors.go:39 start.go:250 start.go:145 start.go:61 cmd.go:50 command.go:985 command.go:1117 command.go:1041 command.go:1034 cmd.go:34 main.go:10 proc.go:271 asm_arm64.s:1222]"
```

Work around is to rerun `omni operator init-nodes` which deletes all states and re-joins the network at a different height

**Comment by corverroos** [comment]
This might be triggered when the snapshot that is being restored contains EVM log events. Still need to verify this.

**Comment by arajasek** [comment]
Hard to repro -- putting in Private Omega for now, but will punt after some time-boxed investigation /  the problem goes away once the "joining network" workstream is done.

**Comment by corverroos** [comment]
Reproduced when joining omega. Download this [archive](https://drive.google.com/file/d/1qVCLHo_mNyypaC2jBpG08rzevXNGHwfJ/view?usp=sharing) to `~/.omni/omega`. Then run `docker compose up`.

The error is trigger from [cometnode.NewNode](https://github.com/omni-network/omni/blob/main/halo/app/start.go#L230).

It is originating from distribution keeper BeginBlocker. Debugging shows that the staking keeper doesn't have any validators (`len(stakingkeeper.GetLastValidators(...)) == 0`). Which points to invalid DB state after blocksync maybe?

Running `iavl-viewer` in `~/.omni/omega/halo` produces the following, so the staking module does have state....:
```
iavl-viewer
Compactions
 Level |   Tables   |    Size(MB)   |    Time(sec)  |    Read(MB)   |   Write(MB)
-------+------------+---------------+---------------+---------------+---------------
   0   |          3 |       2.12151 |       0.00000 |       0.00000 |       0.00000
   1   |          2 |       2.15460 |       0.00000 |       0.00000 |       0.00000
-------+------------+---------------+---------------+---------------+---------------
 Total |          5 |       4.27611 |       0.00000 |       0.00000 |       0.00000

+--------------+--------------+----------------+----------------+------------------+-----------------+
| MODULE       | AVG KEY SIZE | AVG VALUE SIZE | TOTAL KEY SIZE | TOTAL VALUE SIZE | TOTAL KEY PAIRS |
+--------------+--------------+----------------+----------------+------------------+-----------------+
| acc          | 23 B         | 63 B           | 1.3 kB         | 3.5 kB           |              55 |
| attest       | 26 B         | 54 B           | 16.8 kB        | 34.2 kB          |             630 |
| bank         | 23 B         | 29 B           | 303 B          | 385 B            |              13 |
| consensus    | 27 B         | 39 B           | 108 B          | 159 B            |               4 |
| distribution | 34 B         | 39 B           | 2.4 kB         | 2.7 kB           |              69 |
| evidence     | 27 B         | 5 B            | 55 B           | 11 B             |               2 |
| evmengine    | 25 B         | 30 B           | 151 B          | 183 B            |               6 |
| misc         | 7 B          | 318 B          | 15 B           | 636 B            |               2 |
| portal       | 21 B         | 21 B           | 878 B          | 850 B            |              40 |
| registry     | 24 B         | 66 B           | 171 B          | 466 B            |               7 |
| slashing     | 29 B         | 77 B           | 870 B          | 2.3 kB           |              30 |
| staking      | 25 B         | 675 B          | 501.4 kB       | 13.5 MB          |           20054 |
| valsync      | 23 B         | 28 B           | 853 B          | 1.0 kB           |              37 |
+--------------+--------------+----------------+----------------+------------------+-----------------+
| TOTAL        |              |                | 525.2 KB       | 13.6 MB          |           20949 |
+--------------+--------------+----------------+----------------+------------------+-----------------+
```

**Comment by corverroos** [comment]
More logs:
```
halo      | 24-07-31 08:59:56.176 INFO Parsed config from flags                 app-db-backend=goleveldb engine-endpoint=http://omni_evm:8551 engine-jwt-file=/geth/jwtsecret evm-build-delay=600ms evm-build-optimistic=true home=./halo log-color=auto log-format=console log-level=info min-retain-blocks=1 network=omega pruning=default snapshot-interval=1000 snapshot-keep-recent=2 tracing-endpoint="" tracing-headers="" xchain-evm-rpc-endpoints=map[omni_evm:http://omni_evm:8545]
halo      | 24-07-31 08:59:56.193 INFO Starting halo consensus client
halo      | 24-07-31 08:59:56.194 INFO Version info                             version=v0.0.0 git_commit=ad788b3 git_timestamp=2024-07-30T23:45:31Z
halo      | 24-07-31 08:59:56.414 INFO Upgrading IAVL storage for faster queries + execution on live state. This may take a while store_key="KVStoreKey{0xc002b0d070, valsync}" version=0 commit=436F6D6D697449447B5B5D3A307D
halo      | 24-07-31 08:59:56.423 INFO Upgrading IAVL storage for faster queries + execution on live state. This may take a while store_key="KVStoreKey{0xc00035d490, bank}" version=0 commit=436F6D6D697449447B5B5D3A307D
halo      | 24-07-31 08:59:56.424 INFO Upgrading IAVL storage for faster queries + execution on live state. This may take a while store_key="KVStoreKey{0xc0002248b0, slashing}" version=0 commit=436F6D6D697449447B5B5D3A307D
halo      | 24-07-31 08:59:56.425 INFO Upgrading IAVL storage for faster queries + execution on live state. This may take a while store_key="KVStoreKey{0xc000059220, evmengine}" version=0 commit=436F6D6D697449447B5B5D3A307D
halo      | 24-07-31 08:59:56.426 INFO Upgrading IAVL storage for faster queries + execution on live state. This may take a while store_key="KVStoreKey{0xc000058590, consensus}" version=0 commit=436F6D6D697449447B5B5D3A307D
halo      | 24-07-31 08:59:56.427 INFO Upgrading IAVL storage for faster queries + execution on live state. This may take a while store_key="KVStoreKey{0xc002b0c1f0, attest}" version=0 commit=436F6D6D697449447B5B5D3A307D
halo      | 24-07-31 08:59:56.427 INFO Upgrading IAVL storage for faster queries + execution on live state. This may take a while store_key="KVStoreKey{0xc002b0dcf0, portal}" version=0 commit=436F6D6D697449447B5B5D3A307D
halo      | 24-07-31 08:59:56.428 INFO Upgrading IAVL storage for faster queries + execution on live state. This may take a while store_key="KVStoreKey{0xc002dc9740, registry}" version=0 commit=436F6D6D697449447B5B5D3A307D
halo      | 24-07-31 08:59:56.429 INFO Upgrading IAVL storage for faster queries + execution on live state. This may take a while store_key="KVStoreKey{0xc002e6c400, evidence}" version=0 commit=436F6D6D697449447B5B5D3A307D
halo      | 24-07-31 08:59:56.429 INFO Upgrading IAVL storage for faster queries + execution on live state. This may take a while store_key="KVStoreKey{0xc00035dc60, acc}" version=0 commit=436F6D6D697449447B5B5D3A307D
halo      | 24-07-31 08:59:56.430 INFO Upgrading IAVL storage for faster queries + execution on live state. This may take a while store_key="KVStoreKey{0xc000224200, staking}" version=0 commit=436F6D6D697449447B5B5D3A307D
halo      | 24-07-31 08:59:56.431 INFO Upgrading IAVL storage for faster queries + execution on live state. This may take a while store_key="KVStoreKey{0xc0002254b0, distribution}" version=0 commit=436F6D6D697449447B5B5D3A307D
halo      | 24-07-31 08:59:56.451 INFO service start                            module=proxy Starting multiAppConn service            impl=multiAppConn
halo      | 24-07-31 08:59:56.451 INFO service start                            module=proxy module=abci-client connection=query Starting localClient service             impl=localClient
halo      | 24-07-31 08:59:56.452 INFO service start                            module=proxy module=abci-client connection=snapshot Starting localClient service             impl=localClient
halo      | 24-07-31 08:59:56.452 INFO service start                            module=proxy module=abci-client connection=mempool Starting localClient service             impl=localClient
halo      | 24-07-31 08:59:56.452 INFO service start                            module=proxy module=abci-client connection=consensus Starting localClient service             impl=localClient
halo      | 24-07-31 08:59:56.453 INFO service start                            module=events Starting EventBus service                impl=EventBus
halo      | 24-07-31 08:59:56.453 INFO service start                            module=events module=pubsub Starting PubSub service                  impl=PubSub
halo      | 24-07-31 08:59:56.453 INFO Version info                             tendermint_version=0.38.10 abci=2.0.0 block=11 p2p=8 commit_hash=""
halo      | 24-07-31 08:59:56.454 INFO This node is not a validator             module=consensus addr=A4622641302B8CE282CA20546BF974E8FF2D9972 pubKey=PubKeySecp256k1{03B25893C84205C31BAD7E1EB8A0FA2A9E3696236E9B8D1BC3B62F417B68247AB3}
halo      | 24-07-31 08:59:56.466 INFO P2P Node ID                              module=p2p ID=c523bc6f380e855132907fc6a387b4bd3488f071 file=halo/config/node_key.json
halo      | 24-07-31 08:59:56.466 INFO Adding persistent peers                  module=p2p addrs="[623ab30714ecfc8a0c0da0227a1b5bd9cf5b3d8b@seed01.omega.omni.network:26656 7582e893545ecdc8d43402198ccb9100584973b6@seed02.omega.omni.network:26656]"
halo      | 24-07-31 08:59:56.489 INFO Adding unconditional peer ids            module=p2p ids=[]
halo      | 24-07-31 08:59:56.490 INFO Add our address to book                  module=p2p book=halo/config/addrbook.json addr=c523bc6f380e855132907fc6a387b4bd3488f071@0.0.0.0:26656
halo      | 24-07-31 08:59:56.492 INFO Starting CometBFT                        listeners=[Listener(@)]
halo      | 24-07-31 08:59:56.492 INFO service start                            Starting Node service                    impl=Node
halo      | 24-07-31 08:59:56.499 INFO serve                                    module=rpc-server Starting RPC HTTP server on 127.0.0.1:26657
halo      | 24-07-31 08:59:56.501 INFO service start                            module=p2p Starting P2P Switch service              impl="P2P Switch"
halo      | 24-07-31 08:59:56.501 INFO service start                            module=consensus Starting Consensus service               impl=ConsensusReactor
halo      | 24-07-31 08:59:56.502 INFO Reactor                                  module=consensus waitSync=true
halo      | 24-07-31 08:59:56.502 INFO service start                            module=evidence Starting Evidence service                impl=Evidence
halo      | 24-07-31 08:59:56.503 INFO service start                            module=statesync Starting StateSync service               impl=StateSync
halo      | 24-07-31 08:59:56.503 INFO service start                            module=pex Starting PEX service                     impl=PEX
halo      | 24-07-31 08:59:56.503 INFO service start                            module=p2p book=halo/config/addrbook.json Starting AddrBook service                impl=AddrBook
halo      | 24-07-31 08:59:56.505 INFO service start                            module=mempool Starting Mempool service                 impl=Mempool
halo      | 24-07-31 08:59:56.506 INFO service start                            module=blocksync Starting Reactor service                 impl=Reactor
halo      | 24-07-31 08:59:56.507 INFO Ensure peers                             module=pex numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
halo      | 24-07-31 08:59:56.517 INFO Saving AddrBook to file                  module=p2p book=halo/config/addrbook.json size=5
halo      | 24-07-31 08:59:56.521 INFO Starting state sync                      module=statesync
halo      | 24-07-31 08:59:56.523 INFO Downloading trusted light block using options module=statesync module=light
halo      | 24-07-31 08:59:57.323 INFO service start                            module=p2p peer=21089fb9ac2975e4f0b8ef04d5156a7044b44fb1@35.231.24.102:26656 Starting Peer service                    impl="Peer{MConn{35.231.24.102:26656} 21089fb9ac2975e4f0b8ef04d5156a7044b44fb1 out}"
halo      | 24-07-31 08:59:57.323 INFO service start                            module=p2p peer=21089fb9ac2975e4f0b8ef04d5156a7044b44fb1@35.231.24.102:26656 Starting MConnection service             impl=MConn{35.231.24.102:26656}
halo      | 24-07-31 08:59:57.323 INFO service start                            module=p2p peer=7582e893545ecdc8d43402198ccb9100584973b6@35.196.34.109:26656 Starting Peer service                    impl="Peer{MConn{35.196.34.109:26656} 7582e893545ecdc8d43402198ccb9100584973b6 out}"
halo      | 24-07-31 08:59:57.324 INFO service start                            module=p2p peer=7582e893545ecdc8d43402198ccb9100584973b6@35.196.34.109:26656 Starting MConnection service             impl=MConn{35.196.34.109:26656}
halo      | 24-07-31 08:59:57.324 INFO service start                            module=p2p peer=539ede9ce8f17b9f575dcee70c0d619e25d72723@35.227.50.171:26656 Starting Peer service                    impl="Peer{MConn{35.227.50.171:26656} 539ede9ce8f17b9f575dcee70c0d619e25d72723 out}"
halo      | 24-07-31 08:59:57.325 INFO service start                            module=p2p peer=539ede9ce8f17b9f575dcee70c0d619e25d72723@35.227.50.171:26656 Starting MConnection service             impl=MConn{35.227.50.171:26656}
halo      | 24-07-31 08:59:57.325 INFO service start                            module=p2p peer=da193fb14886224840a911ead03a3c7d2afcdbd7@34.73.70.25:26656 Starting Peer service                    impl="Peer{MConn{34.73.70.25:26656} da193fb14886224840a911ead03a3c7d2afcdbd7 out}"
halo      | 24-07-31 08:59:57.326 INFO service start                            module=p2p peer=da193fb14886224840a911ead03a3c7d2afcdbd7@34.73.70.25:26656 Starting MConnection service             impl=MConn{34.73.70.25:26656}
halo      | 24-07-31 08:59:57.327 INFO service start                            module=p2p peer=623ab30714ecfc8a0c0da0227a1b5bd9cf5b3d8b@35.229.66.121:26656 Starting Peer service                    impl="Peer{MConn{35.229.66.121:26656} 623ab30714ecfc8a0c0da0227a1b5bd9cf5b3d8b out}"
halo      | 24-07-31 08:59:57.327 INFO service start                            module=p2p peer=623ab30714ecfc8a0c0da0227a1b5bd9cf5b3d8b@35.229.66.121:26656 Starting MConnection service             impl=MConn{35.229.66.121:26656}
halo      | 24-07-31 08:59:58.610 INFO Discovering snapshots                    module=statesync discoverTime=10s
halo      | 24-07-31 08:59:58.612 INFO Using rpc endpoint to monitor attached omni evm rpc=http://omni_evm:8545
halo      | 24-07-31 08:59:58.614 WARN Halo is syncing
halo      | 24-07-31 08:59:58.635 WARN Attached omni evm is syncing             highest_block=0 current_block=0 tx_indexing=1
halo      | 24-07-31 08:59:59.029 INFO Discovered new snapshot                  module=statesync height=29000 format=3 hash=735C22970FB263834FBD47FBFBC86BD7F241B4D667DE9D5989D6B46B5DF0F264
halo      | 24-07-31 08:59:59.030 INFO Discovered new snapshot                  module=statesync height=28000 format=3 hash=65A22A4878DE23185D797342A1DE103DB3A53824160D964B6C8A6D1560EF85B0
halo      | 24-07-31 09:00:09.187 INFO VerifyHeader                             module=statesync module=light height=29001 hash=D5033D3BC85314420BB183B7BDA183332470FA9C54025793B25CBB302B59F706
halo      | 24-07-31 09:00:11.139 INFO VerifyHeader                             module=statesync module=light height=29002 hash=02215C4615220A2F380AD161E639F37FDB770EA826A87693798857106F510C30
halo      | 24-07-31 09:00:11.720 INFO Offering snapshot to ABCI app            module=statesync height=29000 format=3 hash=735C22970FB263834FBD47FBFBC86BD7F241B4D667DE9D5989D6B46B5DF0F264
halo      | 24-07-31 09:00:11.728 INFO Snapshot accepted, restoring             module=statesync height=29000 format=3 hash=735C22970FB263834FBD47FBFBC86BD7F241B4D667DE9D5989D6B46B5DF0F264
halo      | 24-07-31 09:00:11.732 INFO Fetching snapshot chunk                  module=statesync height=29000 format=3 chunk=0 total=1
halo      | 24-07-31 09:00:11.745 INFO Header has already been verified         module=statesync module=light height=29000 hash=CC00F959047FD86675FA67736DCC9DBE9EA22A37A87AA50C8EEE8B5E2B9DD41D
halo      | 24-07-31 09:00:11.746 INFO Header has already been verified         module=statesync module=light height=29001 hash=D5033D3BC85314420BB183B7BDA183332470FA9C54025793B25CBB302B59F706
halo      | 24-07-31 09:00:11.747 INFO Header has already been verified         module=statesync module=light height=29002 hash=02215C4615220A2F380AD161E639F37FDB770EA826A87693798857106F510C30
halo      | 24-07-31 09:00:13.354 INFO Header has already been verified         module=statesync module=light height=29001 hash=D5033D3BC85314420BB183B7BDA183332470FA9C54025793B25CBB302B59F706
halo      | 24-07-31 09:00:13.358 INFO Header has already been verified         module=statesync module=light height=29000 hash=CC00F959047FD86675FA67736DCC9DBE9EA22A37A87AA50C8EEE8B5E2B9DD41D
halo      | 24-07-31 09:00:20.006 INFO Applied snapshot chunk to ABCI app       module=statesync height=29000 format=3 chunk=0 total=1
halo      | 24-07-31 09:00:20.008 INFO Verified ABCI app                        module=statesync height=29000 appHash=D394A20155CB815D0AE78FACEE6D191A5A0804047CC56588E74AE6C64A762B5B
halo      | 24-07-31 09:00:20.009 INFO Snapshot restored                        module=statesync height=29000 format=3 hash=735C22970FB263834FBD47FBFBC86BD7F241B4D667DE9D5989D6B46B5DF0F264
halo      | 24-07-31 09:00:20.017 INFO service start                            module=blocksync Starting BlockPool service               impl=BlockPool
halo      | 24-07-31 09:00:21.020 INFO no extended commit yet                   module=blocksync height=29001 last_block_height=29000 initial_height=1 max_peer_height=29859
halo      | 24-07-31 09:00:22.020 INFO no extended commit yet                   module=blocksync height=29001 last_block_height=29000 initial_height=1 max_peer_height=29859
omni_evm  | WARN [07-31|09:00:22.279] Post-merge network, but no beacon client seen. Please launch one to follow the chain!
omni_evm  | INFO [07-31|09:00:22.289] Looking for peers                        peercount=2 tried=2 static=0
halo      | 24-07-31 09:00:23.020 INFO no extended commit yet                   module=blocksync height=29001 last_block_height=29000 initial_height=1 max_peer_height=29859
halo      | 24-07-31 09:00:23.460 ERRO Finalize req failed [BUG]                height=29001 err="validator does not exist"
halo      | 24-07-31 09:00:23.461 ERRO error in proxyAppConn.FinalizeBlock      module=state err="validator does not exist"
halo      | panic: Failed to process committed block (29001:D5033D3BC85314420BB183B7BDA183332470FA9C54025793B25CBB302B59F706): validator does not exist
halo      |
halo      | goroutine 312 [running]:
halo      | github.com/cometbft/cometbft/blocksync.(*Reactor).poolRoutine(0xc002063400, 0x1)
halo      | 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.10/blocksync/reactor.go:552 +0x1946
halo      | github.com/cometbft/cometbft/blocksync.(*Reactor).SwitchToBlockSync.func1()
halo      | 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.10/blocksync/reactor.go:161 +0x57
halo      | created by github.com/cometbft/cometbft/blocksync.(*Reactor).SwitchToBlockSync in goroutine 191
halo      | 	/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.10/blocksync/reactor.go:159 +0xfb
halo exited with code 2
```

**Comment by arajasek** [comment]
I looked into this some today, but unfortunately still don't have the root cause. Some findings:
- The staking module doesn't return any valid entries for me: `k.storeService.OpenKVStore(ctx).Iterator(nil,nil)` returns an invalid `Iterator`.
  - @corverroos would be good for you to see if this is the same for you too?
- The `State` object in CometBFT has the correct set of validators, so we're not totally wrong -- it's just that the `staking` module is wrong.
- I think it'd be good to sanity-check the contents of some of the other modules, if that's easy to do. It's possible the DB is corrupted for other modules too, and this is just the first thing we notice?

**Comment by arajasek** [comment]
Spent my afternoon on this, still no luck. Some things I considered, mostly on the "export" half of things:

- Perhaps the store is getting pruned mid-snapshot generation, resulting in us missing some things.
  - AFAIC tell, based on logs, this isn't happening (or at least didn't happen with the latest incident on staging that we've paused)
- We really don't appear to be missing any entries in the staking module:
  - Take a look at logs [here](https://omniops.grafana.net/explore?schemaVersion=1&panes=%7B%22m9y%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnetwork%3D%5C%22staging%5C%22%7D%20%7C%3D%20%60msg%3D%5C%22snapshot%20Done%5C%22%20store%3Dstaking%60%20%7C%20logfmt%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D%7D&orgId=1), we're completely consistent with the number of nodes we export in the staking module
- No other logs in the entire snapshot generation that stand out to me
- The only corrupt module appears to be the `staking` module. If we "skip" that module (don't fail on errors), we successfully run through all the other modules.

**Comment by corverroos** [comment]
I could narrow it down to the following:
- Restoring the current staging height=50k snapshot
- Mostly produces the correct DB.
- But sometimes 5%, the staking module prefix DB results in invalid iterators.
- The underlying btree DB seems to be invalid

If I change [github.com/cosmos/iavl@v1.1.2/import.go#maxBatchSize](http://github.com/cosmos/iavl@v1.1.2/import.go#maxBatchSize) from 10k to 100k, so no batching is performed, then I cannot reproduce the issue anymore.

If I remove the async writing of batches in that file also fixes the issue. So it seems related to async batches in that file.

**Comment by corverroos** [comment]
Ok, I found the root cause, the iavl library doesn't wait for the second-to-last batch to finish writing before it writes the final batch. Pushed an [PR](https://github.com/cosmos/iavl/pull/983/files) to upstream.
